settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: geoget
  path: .
  env:
    DEV: "true"
    LOG_LEVEL: "debug"
  commands:
    run: 
      status: true
  watcher:
    extensions:
    - go
    paths:
    - .
    ignored_paths:
    - .git
    - .realize
    - vendor
